service:
  address: 0.0.0.0:8080
  download_endpoint: 127.0.0.1:8080/downloads/{crate}/{version}
  api_endpoint: 127.0.0.1:8080
  metrics_address: 0.0.0.0:8081
  auth_required: false

index_s3:
  name: "crates"
  endpoint_url: "http://127.0.0.1:9090"
  region: "us-east-1"
  access_key_id: "1234567890"
  access_key_secret: "valid-secret"

store:
  name: "crates"
  endpoint_url: "http://127.0.0.1:9090"
  region: "us-east-1"
  access_key_id: "1234567890"
  access_key_secret: "valid-secret"

auth_allow_full_access_without_any_checks: true